### ISSUE TITLE
Backend can't handle latencies as a float.

### ISSUE THREAD

**Issue by itravers** [ChicoSystems/HostMon#15]
```
    dish.net     638 Thread #: 9 Time: 39494 Thread Running:  5 Job#: 33 Run#:  12679 Run Time:  47989

    java.sql.SQLException: Incorrect integer value: 'ging 192.168.2.1 with 32 bytes of data:reply from 192.168.2.1: bytes=32 time<1' for column 'latency' at row 1
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1094)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4226)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4158)
at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2615)
at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2776)
at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2834)
at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1755)
at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1679)
at DataBase.write(DataBase.java:397)
at DataBase.recordPings(DataBase.java:466)
at DataBase.recordPing(DataBase.java:144)
at RunnablePing.run(RunnablePing.java:35)
at PingThread.run(PingThread.java:49)
    Inserted Latest Pings Into Minute Table
```

**Comment by itravers** [comment]
The backend and frontend can now process floating point numbers 
Front End needs more testing to make sure it is graphing them correctly.
as of:
9a414fefd406c0b49c81ff86e999b987723fbb18
